In [2]:
import pandas as pd
from pathlib import Path

C:\Users\erik\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [4]:
season = '2022-2023'

url_standard = 'https://fbref.com/en/comps/Big5/' + season + '/stats/players/' + season + '-Big-5-European-Leagues-Stats'

In [60]:
df = pd.read_html(url_standard)[0]

In [61]:
df

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                     Rk             Player             Nation
0                     1   Brenden Aaronson             us USA
1                     2    Paxten Aaronson             us USA
2                     3     James Abankwah             ie IRL
3                     4      George Abbott            eng ENG
4                     5   Yunis Abdelhamid             ma MAR
...                 ...                ...                ...
2999               2885    Martin Ødegaard             no NOR
3000               2886        Milan Đurić             ba BIH
3001               2887      Filip Đuričić             rs SRB
3002               2888             Blanco                NaN
3003               2889     Hugo Guillamón                NaN

     Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                    Pos              Squad                Comp
0                 MF,FW       Leeds United  eng Premier League
1                 MF,DF     Eint Frankfurt       de Bundesliga
2                    DF            Udinese          it Serie A
3                    MF          Tottenham  eng Premier League
4                    DF              Reims          fr Ligue 1
...                 ...                ...                 ...
2999                 MF            Arsenal  eng Premier League
3000                 FW      Hellas Verona          it Serie A
3001              MF,FW          Sampdoria          it Serie A
3002                 MF              Cádiz          es La Liga
3003              DF,MF           Valencia          es La Liga

     Unnamed: 6_level_0 Unnamed: 7_level_0 Playing Time         ...  \
                    Age               Born           MP Starts  ...
0                    21               2000           36     28  ...
1                    18               2003            7      0  ...
2                    18               2004            2      1  ...
3                    16               2005            1      0  ...
4                    34               1987           37     37  ...
...                 ...                ...          ...    ...  ...
2999                 23               1998           37     37  ...
3000                 32               1990           28     14  ...
3001                 30               1992           32     27  ...
3002                 22               2000            3      2  ...
3003                 22               2000           25     19  ...

     Per 90 Minutes                                                       \
                Ast   G+A  G-PK G+A-PK    xG   xAG xG+xAG  npxG npxG+xAG
0              0.11  0.15  0.04   0.15  0.15  0.16   0.31  0.15     0.31
1              0.00  0.00  0.00   0.00  0.09  0.03   0.11  0.09     0.11
2              0.00  0.00  0.00   0.00  0.00  0.00   0.00  0.00     0.00
3              0.00  0.00  0.00   0.00  0.00  0.00   0.00  0.00     0.00
4              0.05  0.08  0.03   0.08  0.06  0.03   0.09  0.06     0.09
...             ...   ...   ...    ...   ...   ...    ...   ...      ...
2999           0.20  0.63  0.43   0.63  0.29  0.23   0.52  0.29     0.52
3000           0.07  0.13  0.07   0.13  0.09  0.08   0.18  0.09     0.18
3001           0.00  0.12  0.12   0.12  0.11  0.08   0.19  0.11     0.19
3002           0.00  0.00  0.00   0.00   NaN   NaN    NaN   NaN      NaN
3003           0.22  0.28  0.00   0.22   NaN   NaN    NaN   NaN      NaN

     Unnamed: 37_level_0
                 Matches
0                Matches
1                Matches
2                Matches
3                Matches
4                Matches
...                  ...
2999             Matches
3000             Matches
3001             Matches
3002             Matches
3003             Matches

[3004 rows x 38 columns]

In [62]:
df_copy = df.copy()

In [97]:
df_copy.columns = df_copy.columns.droplevel()

ValueError: Cannot remove 1 levels from an index with 1 levels: at least one level must be left.

In [115]:
df_copy = df_copy.rename(columns={'Rk' : 'ID'})

In [116]:
df_copy.rename(columns={'Pos':'Position'}, inplace = True)

In [117]:
df_copy['Position'] = df_copy['Position'].str[:2]
df_copy

,ID,Player,Nation,Position,Squad,Comp,Age,Born,MP,Starts,...,Ast,G+A,G-PK,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG,Matches
0,1,Brenden Aaronson,us USA,MF,Leeds United,eng Premier League,21,2000,36,28,...,0.11,0.15,0.04,0.15,0.15,0.16,0.31,0.15,0.31,Matches
1,2,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,18,2003,7,0,...,0.00,0.00,0.00,0.00,0.09,0.03,0.11,0.09,0.11,Matches
2,3,James Abankwah,ie IRL,DF,Udinese,it Serie A,18,2004,2,1,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches
3,4,George Abbott,eng ENG,MF,Tottenham,eng Premier League,16,2005,1,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,34,1987,37,37,...,0.05,0.08,0.03,0.08,0.06,0.03,0.09,0.06,0.09,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999,2885,Martin Ødegaard,no NOR,MF,Arsenal,eng Premier League,23,1998,37,37,...,0.20,0.63,0.43,0.63,0.29,0.23,0.52,0.29,0.52,Matches
3000,2886,Milan Đurić,ba BIH,FW,Hellas Verona,it Serie A,32,1990,28,14,...,0.07,0.13,0.07,0.13,0.09,0.08,0.18,0.09,0.18,Matches
3001,2887,Filip Đuričić,rs SRB,MF,Sampdoria,it Serie A,30,1992,32,27,...,0.00,0.12,0.12,0.12,0.11,0.08,0.19,0.11,0.19,Matches
3002,2888,Blanco,NaN,MF,Cádiz,es La Liga,22,2000,3,2,...,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,Matches
3003,2889,Hugo Guillamón,NaN,DF,Valencia,es La Liga,22,2000,25,19,...,0.22,0.28,0.00,0.22,NaN,NaN,NaN,NaN,NaN,Matches

In [118]:
df = df_copy

In [114]:
df_copy = df

In [122]:
df_copy['Nation'] = df_copy['Nation'].str.split(n=1).str[1]

In [127]:
df_copy.rename(columns={'Comp': 'League'}, inplace=True)

In [134]:
df_copy['League'] = df_copy['League'].str.split(n=1).str[1]

In [144]:
df_copy.columns

Index(['ID', 'Player', 'Nation', 'Position', 'Squad', 'League', 'Age', 'Born',
       'MP', 'Starts', 'Min', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK',
       'PKatt', 'CrdY', 'CrdR', 'xG', 'npxG', 'xAG', 'npxG+xAG', 'PrgC',
       'PrgP', 'PrgR', 'Gls', 'Ast', 'G+A', 'G-PK', 'G+A-PK', 'xG', 'xAG',
       'xG+xAG', 'npxG', 'npxG+xAG', 'Matches'],
      dtype='object')

In [154]:
df_copy.drop('90s', axis=1, inplace=True)

KeyError: "['90s'] not found in axis"

In [161]:
columns_to_drop = ['PK','PKatt', 'xG', 'npxG', 'xAG', 'npxG+xAG', 'PrgC', 'PrgP', 'PrgR', 'G+A-PK', 'xG', 'xAG', 'xG+xAG', 'npxG', 'npxG+xAG']
df_copy.drop(columns=columns_to_drop, axis=1, inplace=True)

In [206]:
df_copy

,ID,Player,Nation,Position,Squad,League,Age,Born,MP,Starts,Min,Goals,Assists,G+A,Yellow Cards,Red Cards,Goals per Game,Assists per Game,G+A per Game
0,1,Brenden Aaronson,USA,MF,Leeds United,Premier League,21,2000,36,28,2372,1,3,4,2,0,0.04,0.11,0.15
1,2,Paxten Aaronson,USA,MF,Eint Frankfurt,Bundesliga,18,2003,7,0,173,0,0,0,1,0,0.00,0.00,0.00
2,3,James Abankwah,IRL,DF,Udinese,Serie A,18,2004,2,1,63,0,0,0,0,0,0.00,0.00,0.00
3,4,George Abbott,ENG,MF,Tottenham,Premier League,16,2005,1,0,1,0,0,0,0,0,0.00,0.00,0.00
4,5,Yunis Abdelhamid,MAR,DF,Reims,Ligue 1,34,1987,37,37,3330,1,2,3,6,0,0.03,0.05,0.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999,2885,Martin Ødegaard,NOR,MF,Arsenal,Premier League,23,1998,37,37,3127,15,7,22,4,0,0.43,0.20,0.63
3000,2886,Milan Đurić,BIH,FW,Hellas Verona,Serie A,32,1990,28,14,1366,1,1,2,3,0,0.07,0.07,0.13
3001,2887,Filip Đuričić,SRB,MF,Sampdoria,Serie A,30,1992,32,27,2171,3,0,3,9,0,0.12,0.00,0.12
3002,2888,Blanco,NaN,MF,Cádiz,La Liga,22,2000,3,2,158,0,0,0,0,0,0.00,0.00,0.00
3003,2889,Hugo Guillamón,NaN,DF,Valencia,La Liga,22,2000,25,19,1632,1,4,5,5,0,0.06,0.22,0.28

In [204]:
df.columns.values[18] = 'G+A per Game'

In [198]:
df_copy.drop('Matches', axis=1, inplace=True)

In [170]:
df_copy.drop(df_copy[df_copy['ID'] == 'Rk'].index, inplace=True)

In [207]:
column_to_move = df_copy.pop('Position')
df_copy.insert(7, 'Position', column_to_move)

In [1]:
df_copy.to_csv('footballdata.csv', index=False)

NameError: name 'df_copy' is not defined